import { KeyStatusEmun } from "@/constants/interface";

export const BILL_TYPE: KeyStatusEmun = {
  LR: "手工账",
  XD: "客户订单",
  XS: "配件销售",
  XT: "销售退货",
  CD: "订货计划",
  CG: "配件采购",
  JJ: "急件采购",
  CT: "采购退货",
  DS: "代收对账",
  DZ: "应收付对账",
  SS: "发货运费自付",
  SA: "发货运费垫付",
  SO: "发货运费对付",
  RS: "收货运费自付",
  RA: "收货运费垫付",
  RO: "收货运费对付",
  YJ: "佣金",
  SAO: "发货运费垫付应收款",
  RAO: "收货运费垫付应收款",
  TS: "预收冲销",
  TF: "预付冲销"
};

export const YX_BILL_TYPE: KeyStatusEmun = {
  LR: "手工账",
  XD: "客户订单",
  XS: "配件销售",
  XT: "销售退货",
  CD: "订货计划",
  CG: "配件采购",
  JJ: "急件采购",
  CT: "采购退货",
  DS: "代收对账",
  DZ: "应收付对账",
  SS: "发货运费自付",
  SA: "发货运费垫付",
  SO: "发货运费对付",
  RS: "收货运费自付",
  RA: "收货运费垫付",
  RO: "收货运费对付",
  YJ: "佣金",
  SAO: "发货运费垫付应收款",
  RAO: "收货运费垫付应收款",
  TS: "预收冲销",
  TF: "预付冲销",
  XC: "洗车单",
  WX: "维修单",
  FX: "返修单"
};
